### ISSUE TITLE
如何在四台服务器上启动四个节点的ont私链？

### ISSUE THREAD

**Issue by WhereToFly** [qiluge/VBFT_TPS_TEST#1]
你好，齐撸哥，我想重复一下你的测试过程，但是你的步骤12. start ontology vbft network一句话就带过去了，我不知道怎么启动四个节点的ont私链，因为我只有四台服务器。

撸完请回复哦，谢谢！

**Comment by qiluge** [comment]
歧路歌，谢谢。使用如下命令启动：
```
./ontology --config config.json  \
        --enable-consensus
```

**Comment by WhereToFly** [comment]
好的，歧路歌。如果我想测一下单节点模式下的TPS，需要在你原来的15个步骤里面做哪些修改呢？
